#************************** Cecilia-test v.1.0 config file **************************#

#********** MIT LICENSE - Copyright © 2022 Gian M.N. Benucci, Ph.D. **********#
#*********************** email: benucci[at]msu[dot]edu ***********************#

echo "===> Reading the config.yaml file"

#************* ALL THE FIELDS BELOW MUST BE SELECTED BY THE USER *************#
#=============================================================================#
project_dir="/mnt/home/benucci/Cecilia"

# Change your MSUusername based on MSU ID 
MSUusername="benucci"

# Databases
euk_db="/mnt/home/benucci/CONSTAX_taxonomy/dbs/UNITE/sh_general_release_dynamic_s_all_29.11.2022_dev.fasta"
bac_db="/mnt/home/benucci/CONSTAX_taxonomy/dbs/SILVA/SILVA_138_SSURef_tax_silva_bact_arch.fasta"
bonito_isolates="/mnt/home/benucci/CONSTAX_taxonomy/dbs/isolates_bonitolab2021.fasta"
kevin_synt="/mnt/home/benucci/CONSTAX_taxonomy/dbs/synthetic_kevin.fasta"
phix_db="/mnt/research/ShadeLab/Benucci/databases/phix_index/my_phix"

# These are the main Cecilia-test run-related parameters - very important!
# For details about these parameters, refer to the README.md file.
DNAmarker=16S
R1=yes
R2=no
assemble=no
rename=yes
stripleft=no
stripleft_bp=0
max_Eerr=1.0
test_length=yes
cluster_otu=no
cluster_asv=yes
cluster_swarm=no

# constax2 parameters - very important!
SINTAX=/mnt/research/rdp/public/thirdParty/usearch11.0.667_i86linux64
RDP=/mnt/home/benucci/anaconda2/envs/constax2/share/rdptools-2.0.3-1/classifier
CONSTAX=/mnt/home/benucci/anaconda2/envs/constax2/opt/constax-2.0.19-0
train_db=no
trainfiles_euk="/mnt/home/benucci/CONSTAX_taxonomy/dbs/UNITE/trainfiles_unite29112022"
trainfiles_bac="/mnt/home/benucci/CONSTAX_taxonomy/dbs/SILVA/trainfiles_silva138"
constax_conf=0.7

#Add the primers used in the library prep. Some are listed, but maybe you need to add.
#fwd_primer="TATYGYTCTTNAACGAGGAATC" # amf fwd primer (Author here)
#rev_primer="AACACTCGCAYAYATGYTAGA" # amf rev primer
#rev_primer_RC="TCTARCATRTRTGCGAGTGTT" # amf rev compl

#fwd_primer="CTTGGTCATTTAGAGGAAGTAA" # ITS1F fwd primer (Gardes & Bruns 1993)
#rev_primer="TCCTCCGCTTATTGATATGC" # ITS4 rev primer (White et al. 1990)
#rev_primer_RC="GCATATCAATAAGCGGAGGA" # ITS4 rev compl

#fwd_primer="CTTGGTCATTTAGAGGAAGTAA" # ITS1F fwd primer (White et al. 1990)
#rev_primer="GCTGCGTTCTTCATCGATGC" # ITS2 rev primer (White et al. 1990)
#rev_primer_RC="GCATCGATGAAGAACGCAGC" # ITS2 rev compl

fwd_primer="GTGCCAGCMGCCGCGGTAA" # 515F fwd primer (Parada et al., 2016 modified by Caporaso)
rev_primer="GGACTACHVGGGTWTCTAAT" # 806R rev primer (Apprill et al., 2015. modified by Caporaso)
rev_primer_RC="ATTAGAWACCCBDGTAGTCC" # 806R rev compl https://earthmicrobiome.org/protocols-and-standards/16s/

#****************************** END OF USER INPUT **************************#
#===========================================================================#
